feat: Design interfaces and implement concrete implementation classes and configuration parameters
xiaxuchen/get-jobs-boss pull request #3
Opened 2024-08-28 15:01 UTC by Think-404

设计接口和实现具体实现类以及配置化参数

2024-08-29 06:59 UTC, Think-404 commented
> 设计接口和实现具体实现类以及配置化参数

2024-08-29 07:10 UTC, xiaxuchen requested changes

2024-08-29 07:10 UTC, xiaxuchen commented on src/main/java/ResumeSub.java
> + */
去掉

2024-08-29 07:10 UTC, xiaxuchen commented on src/main/java/BossResumeSub.java
> +        loginUrl= props.getProperty("login.url");
配置文件的职责拆分出去，由一个接口单独负责

2024-08-29 07:10 UTC, xiaxuchen commented on src/main/java/BossResumeSub.java
> +import lombok.SneakyThrows;
别放在根，放在一个包下面

2024-08-30 09:36 UTC, xiaxuchen commented on src/main/java/org/originit/MainApplication.java
> +        bossResumeSub.login();
为什么会是执行login呢？如果是login的话，那么按照语义岂不是只会login？看看模板方法模式

2024-08-30 09:36 UTC, xiaxuchen commented on src/main/java/org/originit/utils/TelegramNotificationBot.java
这明显不是util

2024-08-30 09:36 UTC, xiaxuchen commented on src/main/java/org/originit/operator/impl/BossResumeSub.java
> +    @SneakyThrows
少用吧，用正常的

2024-08-30 09:56 UTC, closed without merging